/**
 * OpenResty infrastructure provider - routing + SSL for self-hosted deployments.
 *
 * Writes server block config files to a directory that OpenResty `include`s,
 * then reloads. SSL is handled by certbot (Let's Encrypt) running
 * as a separate process - OpenResty just reads the cert files.
 *
 * This provider works with BOTH Docker and Bare runtimes.
 *
 * Typical nginx.conf inside OpenResty:
 * ```
 * http {
 *   include /usr/local/openresty/nginx/conf/sites-enabled/*;
 * }
 * ```
 */

import {
  access as fsAccess,
  writeFile as fsWriteFile,
  rm as fsRm,
  mkdir as fsMkdir,
  readFile as fsReadFile,
  rename as fsRename,
  stat as fsStat,
} from "node:fs/promises";
import { execFile as cpExecFile } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { promisify } from "node:util";
import { dirname, join } from "node:path";

import type { CommandExecutor, ManualCert, RouteConfig, SslResult } from "../types";
import type { RoutingProvider, SslProvider } from "./types";
import { LUA_LOGGER_PATH, RULES_GUARD_PATH, luaSourceAvailable, buildReloadCommand, detectOpenRestyPaths, ACME_HTTP01_PORT, ACME_CHALLENGE_LOCATION, type OpenRestyPaths } from "./openresty-lua";
import { safeErrorMessage, sanitizeProxySettings, resolveRedirectStatus, PROXY_GZIP_TYPES, type ProxySettings } from "@repo/core";
import { sq } from "../system/local-shell";
import { BOOTSTRAP_CERT_SEGMENT, validateCertFor } from "../system/proxy/cert-material";
import { probeStaticOutput, type OutputProbeResult } from "../system/output-exists";

/**
 * Reverse-proxy headers shared by every proxy_pass location.
 *
 * X-Forwarded-Proto carries `$openship_fwd_proto`, not `$scheme` — see
 * {@link FORWARD_VARS}. Every server block generated by `registerRoute` defines
 * that variable, and these headers are only ever emitted inside those blocks.
 */
const PROXY_HEADERS = `proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $openship_fwd_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";`;

/**
 * Per-request vars every generated server block opens with.
 *
 * Both exist because a CDN in front of us may terminate TLS and then reach origin
 * on plain :80 (Cloudflare's "Flexible" SSL mode is the common case):
 *
 *   $openship_redirect_https — an unconditional `301 → https` on :80 sends such a
 *     request back to the CDN, which comes back here on :80: an infinite redirect
 *     loop. Only bounce a request that really arrived over HTTP.
 *   $openship_fwd_proto — overwriting the CDN's X-Forwarded-Proto with `$scheme`
 *     tells the app "http" for a request the browser made over https, which breaks
 *     app-generated absolute URLs, secure cookies, and framework HTTPS guards.
 *
 * Built-in variables only, deliberately: an http-level `map` would have to be
 * shipped in the edge's nginx.conf, and a vhost referencing a variable an
 * already-deployed edge doesn't define fails `openresty -t` — which means the
 * reload is refused and registerRoute rolls the route back. This template has to
 * stay valid on an edge running an older image.
 *
 * Only an EXACT "https" is honoured, and the literal `https` is what gets forwarded
 * — never the client's own string. A chained-proxy header is legally a list
 * ("http, https"), and passing that through verbatim confuses frameworks that
 * compare it to "https"; anything unrecognised falls back to `$scheme`.
 *
 * X-Forwarded-Proto is client-spoofable on a directly-exposed box. All a client
 * gains by lying is skipping its OWN redirect (and telling the app its own request
 * was https) — it can't affect anyone else's traffic, and it could simply have
 * used https to begin with.
 */
const FORWARD_VARS = `    set $openship_fwd_proto $scheme;
    set $openship_redirect_https 1;
    if ($http_x_forwarded_proto = "https") {
        set $openship_fwd_proto https;
        set $openship_redirect_https 0;
    }`;

/** Render extra path-prefix proxy locations (composite single-domain routing). */
function renderProxyLocations(route: RouteConfig): string {
  if (!route.proxyLocations || route.proxyLocations.length === 0) return "";
  return route.proxyLocations
    .map((loc) => {
      assertValidUpstream(loc.targetUrl);
      return `
    location ${loc.pathPrefix} {
        proxy_pass ${loc.targetUrl};
        ${PROXY_HEADERS}
    }`;
    })
    .join("");
}

/**
 * The `location /` body for a route that redirects to another host, or null when
 * it serves normally.
 *
 * `assertValidDomain` runs on the TARGET, not just the route's own domain: the
 * target is interpolated into the emitted config, so an unvalidated one would be
 * a config-injection vector even though it reached us through a validating API.
 * `resolveRedirectStatus` (shared with the API's validator, @repo/core) falls back
 * to 301 rather than emitting `return 0` and making `openresty -t` reject the
 * whole vhost.
 */
function renderHostRedirect(route: RouteConfig): string | null {
  const redirect = route.redirectHost;
  if (!redirect?.target) return null;
  assertValidDomain(redirect.target);
  return `return ${resolveRedirectStatus(redirect.statusCode)} https://${redirect.target}$request_uri;`;
}

/** Render vercel.json `redirects` as `return <code> <dest>` locations. */
function renderRedirects(route: RouteConfig): string {
  if (!route.redirects || route.redirects.length === 0) return "";
  return route.redirects
    .map(
      (r) => `
    location ${r.exact ? "= " : ""}${r.path} {
        return ${r.statusCode} ${r.destination};
    }`,
    )
    .join("");
}

/**
 * Render GLOBAL (source `/(.*)` → path `/`) header rules as server-scope
 * `add_header … always;`. Path-scoped header rules are skipped here (they'd
 * need a dedicated location that could shadow proxy/static behavior) — the
 * common case is global security headers.
 */
function renderServerHeaders(route: RouteConfig): string {
  const global = (route.headerRules ?? []).filter((rule) => rule.path === "/");
  const lines = global.flatMap((rule) =>
    rule.headers.map((h) => `    add_header ${h.key} "${h.value.replace(/"/g, '\\"')}" always;`),
  );
  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

/**
 * Render the curated reverse-proxy tunables (client_max_body_size, proxy/body
 * timeouts, buffering, gzip) as server-scope directives. Re-validates every
 * value via `sanitizeProxySettings` before emitting — a malformed value is
 * DROPPED, never interpolated raw into the config (defense-in-depth over the
 * API schema; keeps `nginx -t` safe). gzip emits a FIXED, safe type set.
 */
export function renderProxyOptions(proxy?: ProxySettings | null): string {
  const p = sanitizeProxySettings(proxy);
  if (!p) return "";
  const lines: string[] = [];
  if (p.clientMaxBodySize) lines.push(`    client_max_body_size ${p.clientMaxBodySize};`);
  if (p.proxyReadTimeout) lines.push(`    proxy_read_timeout ${p.proxyReadTimeout};`);
  if (p.proxySendTimeout) lines.push(`    proxy_send_timeout ${p.proxySendTimeout};`);
  if (p.clientBodyTimeout) lines.push(`    client_body_timeout ${p.clientBodyTimeout};`);
  if (p.proxyBuffering !== undefined) {
    lines.push(`    proxy_buffering ${p.proxyBuffering ? "on" : "off"};`);
  }
  if (p.gzip !== undefined) {
    lines.push(`    gzip ${p.gzip ? "on" : "off"};`);
    if (p.gzip) {
      lines.push(`    gzip_types ${PROXY_GZIP_TYPES};`);
      lines.push(`    gzip_min_length 1024;`);
    }
  }
  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

// ─── Rate Limit Config ──────────────────────────────────────────────────────

export interface RateLimitConfig {
  /** Requests per second (0 = disabled) */
  rps: number;
  /** Burst allowance (extra requests above rate, queued with nodelay) */
  burst: number;
  /** CIDR strings whitelisted from rate limiting (e.g. ["127.0.0.1/32", "10.0.0.0/8"]) */
  whitelist: string[];
}

/**
 * Render the `geo $whitelist` body for the rate-limit snippet: the loopback
 * defaults plus one `<cidr> 1;` entry per whitelisted CIDR.
 *
 * Exported for testing.
 */
export function renderGeoEntries(whitelist: readonly string[]): string[] {
  const entries = [
    "        default         0;",
    "        127.0.0.1/32    1;",
    "        ::1/128         1;",
  ];
  for (const cidr of whitelist) {
    // Validate CIDR format loosely (prevents injection)
    if (/^[\da-fA-F.:\/]+$/.test(cidr) && cidr.length <= 50) {
      // `padEnd(15)` plus an explicit space keeps the historical 16-column
      // alignment for short CIDRs, while still separating longer ones. Padding
      // to 16 with no space is a no-op once the CIDR is already >= 16 chars,
      // which emits `192.168.100.0/241;` - nginx then reads an address with no
      // value and `openresty -t` fails, rolling the whole change back.
      entries.push(`        ${cidr.padEnd(15)} 1;`);
    }
  }
  return entries;
}

// ─── Config ──────────────────────────────────────────────────────────────────

export interface NginxProviderOptions {
  /**
   * Detected OpenResty paths - from detectOpenRestyPaths().
   * Every path (sitesDir, confPath, bin, pid) comes from here.
   */
  paths: OpenRestyPaths;
  /**
   * ACME email for certbot certificate registration.
   */
  acmeEmail?: string;
  /** Alternate ACME directory. Unset preserves Certbot's Let's Encrypt default. */
  acmeDirectoryUrl?: string;
  /** EAB key identifier. Must be supplied together with acmeEabHmacKey. */
  acmeEabKid?: string;
  /** Base64url-encoded EAB HMAC key. Written only to a short-lived 0600 file. */
  acmeEabHmacKey?: string;
  /** Certificate private-key algorithm/size. Unset preserves Certbot's default. */
  acmeKeyType?: "ec256" | "ec384" | "rsa2048" | "rsa4096";
  /** Trust bundle visible to the Certbot execution environment. */
  acmeCaBundle?: string;
  /** Whether to accept the selected CA's terms. Defaults to the historic true. */
  acmeTosAgreed?: boolean;
  /**
   * Path to Let's Encrypt live certificate directory.
   * Default: /etc/letsencrypt/live
   */
  certDir?: string;
  /**
   * Command executor for file operations.
   * When provided, all ops go through the executor (SSH remote).
   * When omitted, uses node:fs directly (local).
   */
  executor?: CommandExecutor;
  /**
   * Treat `paths` as authoritative and skip the per-reload re-detection.
   *
   * REQUIRED for a containerized edge. Re-detection runs `openresty -V`, which on
   * an edge executor answers from INSIDE the container and reports container
   * paths — while file ops land on the host. Left unpinned, the first reload would
   * silently repoint `sitesDir` at a host directory nothing serves from.
   */
  pinPaths?: boolean;
  /**
   * This edge is a CONTAINER and commands run INSIDE it, so the OpenResty master
   * is pid 1 — see buildReloadCommand. Set by the two container-edge builders in
   * proxy/ensure-container-edge.ts; never inferred, because guessing it wrong
   * means a failed reload kills the container and 502s every site.
   */
  containerEdge?: boolean;
}

const DEFAULT_CERT_DIR = "/etc/letsencrypt/live";

/** Certbot's implicit default when no `--server` is passed — what every lineage
 * issued before alternate-CA support (or with no directory configured) records. */
const LETSENCRYPT_PRODUCTION_DIRECTORY = "https://acme-v02.api.letsencrypt.org/directory";

export type AcmeKeyType = NonNullable<NginxProviderOptions["acmeKeyType"]>;

function assertValidAcmeOptions(opts: NginxProviderOptions): void {
  if (!!opts.acmeEabKid !== !!opts.acmeEabHmacKey) {
    throw new Error("ACME EAB requires both a key identifier and an HMAC key");
  }
  if (opts.acmeDirectoryUrl) {
    let directory: URL;
    try {
      directory = new URL(opts.acmeDirectoryUrl);
    } catch {
      throw new Error("ACME directory must be a valid http(s) URL");
    }
    if (directory.protocol !== "https:" && directory.protocol !== "http:") {
      throw new Error("ACME directory must use http or https");
    }
  }
  if (opts.acmeEabKid && (!/^[\x20-\x7E]+$/.test(opts.acmeEabKid) || opts.acmeEabKid.length > 512)) {
    throw new Error("ACME EAB key identifier must be printable ASCII (maximum 512 characters)");
  }
  if (opts.acmeEabHmacKey && !/^[A-Za-z0-9_-]+={0,2}$/.test(opts.acmeEabHmacKey)) {
    throw new Error("ACME EAB HMAC key must be base64url encoded");
  }
  if (opts.acmeCaBundle && !opts.acmeCaBundle.startsWith("/")) {
    throw new Error("ACME CA bundle must be an absolute path in the Certbot environment");
  }
}

export function acmeKeyArgs(keyType?: AcmeKeyType): string[] {
  switch (keyType) {
    case "ec256": return ["--key-type", "ecdsa", "--elliptic-curve", "secp256r1"];
    case "ec384": return ["--key-type", "ecdsa", "--elliptic-curve", "secp384r1"];
    case "rsa2048": return ["--key-type", "rsa", "--rsa-key-size", "2048"];
    case "rsa4096": return ["--key-type", "rsa", "--rsa-key-size", "4096"];
    default: return [];
  }
}

/** Only allow valid domain characters - prevents shell injection. */
const DOMAIN_RE = /^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$/;

function assertValidDomain(domain: string): void {
  if (!DOMAIN_RE.test(domain) || domain.length > 253) {
    throw new Error(`Invalid domain: ${domain}`);
  }
}

/**
 * `proxy_pass`/`root` values are interpolated verbatim into the generated
 * server{} block and — on proxy adopt/takeover — come from PARSING A FOREIGN
 * proxy config (semi-trusted). Reject anything that could break out of the
 * single-token directive and inject arbitrary nginx config. `openresty -t` only
 * catches MALFORMED output, so a well-formed injection would otherwise slip in.
 * Normal deploy targets (`http://127.0.0.1:3000`, `/var/www/app`) contain none
 * of these chars, so this never rejects a legitimate route.
 */
function assertNoNginxInjection(value: string, what: string): void {
  if (/[\s;{}#\\]/.test(value)) {
    throw new Error(`Invalid ${what} (contains characters that could inject nginx config): ${value}`);
  }
}

function assertValidUpstream(targetUrl: string): void {
  assertNoNginxInjection(targetUrl, "proxy target");
  if (!/^https?:\/\/.+/.test(targetUrl)) {
    throw new Error(`Invalid proxy target (must be http/https URL): ${targetUrl}`);
  }
}

/**
 * Every directory an Openship-managed static route may serve from lives under here
 * (build output at `/opt/openship/static/...`, bare release dirs at
 * `/opt/openship/<project>/...`).
 */
export const MANAGED_STATIC_BASE = "/opt/openship";

/**
 * Validate a doc root before it becomes a public `root` directive.
 *
 * Absolute + no traversal + no injection was NOT enough: it accepted any path on the
 * box, so a wrong value anywhere upstream would have published that directory to the
 * internet ("routing can only go under the project's own output" was the intent, but
 * nothing enforced it). Managed roots are now confined to
 * {@link MANAGED_STATIC_BASE}; only an explicitly adopted root may sit outside it.
 *
 * Confinement is on the PREFIX plus a separator so `/opt/openship-evil` cannot pass
 * as a child of `/opt/openship`.
 */
function assertValidStaticRoot(root: string, opts?: { adopted?: boolean }): void {
  assertNoNginxInjection(root, "static root");
  if (!root.startsWith("/") || root.includes("..")) {
    throw new Error(`Invalid static root (must be an absolute path, no traversal): ${root}`);
  }
  if (opts?.adopted) return;
  const confined = root === MANAGED_STATIC_BASE || root.startsWith(`${MANAGED_STATIC_BASE}/`);
  if (!confined) {
    throw new Error(
      `Refusing to serve static root outside ${MANAGED_STATIC_BASE}: ${root}. ` +
        `Openship-managed routes serve only their own build output; pass ` +
        `staticRootAdopted when importing a root an existing proxy already serves.`,
    );
  }
}

const execFileAsync = promisify(cpExecFile);

/**
 * Turn certbot's verbose failure output into ONE actionable line.
 *
 * certbot buries the cause in a `Type:` / `Detail:` / `Hint:` block and opens with
 * boilerplate ("Saving debug log to …") that tells the operator nothing. Pull the
 * meaningful lines and map the common HTTP-01 failure shapes to a plain-English
 * diagnosis so a failed cert says WHY — DNS, firewall/port-80, or a proxy still on
 * :80 — instead of the opaque opener.
 */
export function summarizeCertbotFailure(output: string, domain: string): string {
  const text = output || "";
  const pick = (re: RegExp) => text.match(re)?.[0]?.replace(/\s+/g, " ").trim();
  const detail = pick(/Detail:\s*[^\n]+/i);
  const hint = pick(/Hint:\s*[^\n]+/i);

  let diagnosis: string | undefined;
  if (/timeout during connect|connection refused|failed to connect|Timeout/i.test(text)) {
    diagnosis =
      `Port 80 for ${domain} isn't reachable from the internet — a firewall / cloud security group ` +
      `is blocking it, the domain doesn't point at this server, or another proxy is still bound to :80.`;
  } else if (/NXDOMAIN|no\s+(A|AAAA)\s+record|DNS problem|could not be resolved|no records? found/i.test(text)) {
    diagnosis =
      `${domain} doesn't resolve to this server yet — the DNS A record is missing or hasn't propagated. ` +
      `Wait for propagation, then retry from the Domains tab.`;
  } else if (/\b52[56]\b|ssl handshake failed|cloudflare/i.test(text)) {
    // MUST precede the 40x branch: certbot reports this as "Invalid response from
    // …", which that branch's /invalid response/ would otherwise claim.
    //
    // Cloudflare answered the challenge itself instead of forwarding it: its proxy
    // redirected the plain-HTTP request to https ("Always Use HTTPS" / Automatic
    // HTTPS Rewrites / a redirect rule) and then couldn't complete TLS to origin.
    // 525 means it refused our handshake, 526 that it wouldn't accept our
    // certificate — Full (Strict) rejecting the temporary self-signed cert we serve
    // while waiting for this very issuance.
    diagnosis =
      `Cloudflare's proxy is answering the certificate challenge for ${domain} instead of forwarding ` +
      `it to this server: it redirects the request to HTTPS, then rejects the origin's TLS. Fix it one ` +
      `of three ways — set SSL/TLS → Overview to "Full" (not "Full (strict)") until the first ` +
      `certificate is issued, or turn the orange cloud off for this record until it is, or upload a ` +
      `Cloudflare Origin CA certificate from the Domains tab and skip Let's Encrypt entirely.`;
  } else if (/404|invalid response|unauthorized|"?status"?:?\s*40\d/i.test(text)) {
    diagnosis =
      `Port 80 answered but not with our ACME challenge — another web server is still serving :80, so ` +
      `the takeover didn't complete. Re-run and choose take-over / migrate.`;
  } else if (/too many certificates|rateLimited|rate limit/i.test(text)) {
    diagnosis = `Let's Encrypt rate limit reached for ${domain} — wait before retrying.`;
  }

  const parts = [diagnosis, detail, hint].filter(Boolean);
  if (parts.length > 0) return parts.join(" — ");

  // Nothing structured matched — surface the last non-empty lines (the tail holds
  // the real error) rather than the "Saving debug log" opener.
  const lines = text.split("\n").map((l) => l.trim()).filter(Boolean);
  return lines.slice(-3).join(" · ") || `certbot failed to issue a certificate for ${domain}`;
}

interface FileSnapshot {
  exists: boolean;
  content?: string;
}


// ─── Implementation ──────────────────────────────────────────────────────────

export class NginxProvider implements RoutingProvider, SslProvider {
  private sitesDir: string;
  private readonly acmeEmail: string | undefined;
  private readonly acmeDirectoryUrl: string | undefined;
  private readonly acmeEabKid: string | undefined;
  private readonly acmeEabHmacKey: string | undefined;
  private readonly acmeKeyType: AcmeKeyType | undefined;
  private readonly acmeCaBundle: string | undefined;
  private readonly acmeTosAgreed: boolean;
  private readonly certDir: string;
  private readonly executor: CommandExecutor | null;
  private reloadCommand: string;
  private readonly pinPaths: boolean;
  private readonly containerEdge: boolean;

  constructor(opts: NginxProviderOptions) {
    assertValidAcmeOptions(opts);
    this.sitesDir = opts.paths.sitesDir;
    this.acmeEmail = opts.acmeEmail;
    this.acmeDirectoryUrl = opts.acmeDirectoryUrl;
    this.acmeEabKid = opts.acmeEabKid;
    this.acmeEabHmacKey = opts.acmeEabHmacKey;
    this.acmeKeyType = opts.acmeKeyType;
    this.acmeCaBundle = opts.acmeCaBundle;
    this.acmeTosAgreed = opts.acmeTosAgreed ?? true;
    this.certDir = opts.certDir ?? DEFAULT_CERT_DIR;
    this.executor = opts.executor ?? null;
    this.containerEdge = opts.containerEdge ?? false;
    this.reloadCommand = buildReloadCommand(opts.paths, { containerEdge: this.containerEdge });
    this.pinPaths = opts.pinPaths ?? false;
  }

  // ── File operation helpers (dual-path: local or remote) ──────────────

  private async _writeFile(path: string, content: string, mode?: number): Promise<void> {
    // Random suffix (not just pid+ms) so two same-ms writes to the same conf
    // can't collide on the temp path and defeat the atomic rename.
    const tmpPath = `${path}.tmp-${process.pid}-${Date.now()}-${randomBytes(4).toString("hex")}`;

    if (this.executor) {
      try {
        await this.executor.writeFile(tmpPath, content);
        // Tighten perms on the TEMP file, before the rename publishes it — rename
        // preserves the source's mode, so the final path never exists more open
        // than requested. (executor.writeFile has no mode parameter.)
        if (mode !== undefined) {
          await this.executor.exec(`chmod ${sq(mode.toString(8))} ${sq(tmpPath)}`);
        }
        // `rename` (a FILE op), not `exec("mv")`. On a container edge, commands run
        // INSIDE the container while file ops land on the HOST — so the mv renamed a
        // path the container can't see and failed with ENOENT on the file we had just
        // written ("mv: can't rename '…/x.conf.tmp-…': No such file or directory"),
        // taking routing down while the deploy reported success. The shell fallback is
        // correct for any executor whose commands and files share one namespace.
        if (this.executor.rename) {
          await this.executor.rename(tmpPath, path);
        } else {
          await this.executor.exec(`mv ${sq(tmpPath)} ${sq(path)}`);
        }
      } catch (err) {
        await this.executor.rm(tmpPath).catch(() => undefined);
        throw err;
      }
    } else {
      await fsMkdir(dirname(path), { recursive: true });
      try {
        // `mode` applies at creation, so the content is never on disk more open
        // than requested (no chmod-after-write window).
        await fsWriteFile(tmpPath, content, { encoding: "utf-8", mode });
        await fsRename(tmpPath, path);
      } catch (err) {
        await fsRm(tmpPath).catch(() => undefined);
        throw err;
      }
    }
  }

  private async _readFile(path: string): Promise<string> {
    if (this.executor) {
      return this.executor.readFile(path);
    }
    return fsReadFile(path, "utf-8");
  }

  private async _exists(path: string): Promise<boolean> {
    if (this.executor) {
      return this.executor.exists(path);
    }

    try {
      await fsAccess(path);
      return true;
    } catch {
      return false;
    }
  }

  private async _rm(path: string): Promise<void> {
    if (this.executor) {
      await this.executor.rm(path);
    } else {
      try {
        // recursive: every CommandExecutor.rm is `rm -rf`, and callers pass DIRS as
        // well as files (staged cert dirs, the bootstrap cert dir). A plain fsRm
        // throws on a directory, and the catch below would swallow it — leaving the
        // directory behind on the local path only.
        await fsRm(path, { recursive: true, force: true });
      } catch {
        // Already gone
      }
    }
  }

  private async _mkdir(path: string): Promise<void> {
    if (this.executor) {
      await this.executor.mkdir(path);
    } else {
      await fsMkdir(path, { recursive: true });
    }
  }

  /**
   * Put `fullchain.pem` + `privkey.pem` in `dir` as ONE atomic step.
   *
   * Both files are written into a temp sibling dir, then the pair is moved into
   * place together. A cert and its key are only valid as a set — writing them
   * individually means a crash, a full disk, or a dropped SSH connection between
   * the two leaves the new cert next to the previous key, and `openresty -t` then
   * fails for the WHOLE edge (every domain, not just this one) until someone
   * notices. `mv -T`/rename of the staged dir also means a concurrent reload sees
   * either the old pair or the new one, never a half-written PEM.
   */
  private async stageCertDir(dir: string, cert: ManualCert): Promise<void> {
    const staging = `${dir}.staging-${process.pid}-${randomBytes(4).toString("hex")}`;
    try {
      await this._mkdir(staging);
      await this._writeFile(join(staging, "fullchain.pem"), cert.certPem);
      await this._writeFile(join(staging, "privkey.pem"), cert.keyPem);
      if (this.executor) {
        // `mv staging/* dir/` (not `mv staging dir`) so an EXISTING cert dir is
        // updated rather than nested inside itself, and certbot's own sibling
        // files (cert.pem, chain.pem, README) are left alone.
        await this._mkdir(dir);
        await this.executor.exec(
          `mv -f ${sq(join(staging, "fullchain.pem"))} ${sq(join(staging, "privkey.pem"))} ${sq(dir)}/`,
        );
      } else {
        await fsMkdir(dir, { recursive: true });
        await fsRename(join(staging, "fullchain.pem"), join(dir, "fullchain.pem"));
        await fsRename(join(staging, "privkey.pem"), join(dir, "privkey.pem"));
      }
    } finally {
      await this._rm(staging).catch(() => undefined);
    }
  }

  /**
   * Where a domain's temporary self-signed cert lives — a SIBLING of certbot's
   * `live/`, deliberately not inside it. See {@link ensureBootstrapCert}.
   */
  private bootstrapCertDir(domain: string): string {
    return join(dirname(this.certDir), BOOTSTRAP_CERT_SEGMENT, domain);
  }

  /**
   * Ensure a self-signed placeholder cert exists for `domain`, so a route whose TLS
   * we terminate can ALWAYS complete a TLS handshake — including before certbot has
   * issued anything.
   *
   * Why a missing :443 block is a hard failure, not a soft one: an unmatched SNI
   * falls through to the edge's `ssl_reject_handshake` default (correct — it stops
   * unrouted hosts being cross-served someone else's cert). But that means the
   * origin REFUSES the handshake for a domain we do route. Behind Cloudflare's
   * proxy every visitor sees error 525, and issuance deadlocks: Cloudflare answers
   * the HTTP-01 challenge with a 301 to https, then can't reach an origin that
   * refuses TLS, so the challenge fails and the vhost stays HTTP-only — forever
   * (#308). A placeholder breaks the loop: Cloudflare "Full" accepts it, the
   * challenge completes, and the real cert takes over.
   *
   * Deliberately NOT written under `certDir`: `certsExist()` / `readCertInfo()`
   * read that path, so a self-signed cert there would short-circuit provisionCert
   * and report an untrusted cert as `active`, with the renewal scheduler and the
   * verify-pending sweep both satisfied. Keeping it in a sibling dir means cert
   * STATUS is untouched — the domain still reads provisioning/error and keeps
   * retrying until a real cert lands.
   *
   * Returns null when nothing could be produced (no `openssl` on the executor, exec
   * failure); the caller falls back to an HTTP-only vhost, exactly as before.
   * Never throws — a placeholder must not be able to fail a deploy.
   */
  private async ensureBootstrapCert(
    domain: string,
  ): Promise<{ certPath: string; keyPath: string } | null> {
    const dir = this.bootstrapCertDir(domain);
    const certPath = join(dir, "fullchain.pem");
    const keyPath = join(dir, "privkey.pem");

    try {
      if ((await this._exists(certPath)) && (await this._exists(keyPath))) {
        return { certPath, keyPath };
      }
    } catch {
      return null;
    }

    const staging = `${dir}.staging-${process.pid}-${randomBytes(4).toString("hex")}`;
    try {
      await this._mkdir(staging);
      // 10 years: nothing ever trusts this cert (Cloudflare "Full" doesn't validate
      // it, a direct visitor gets a warning), so a short life buys no security —
      // while an EXPIRED placeholder would put the domain back to refusing
      // handshakes, which is the bug this exists to prevent.
      await this._exec("openssl", [
        "req", "-x509", "-newkey", "rsa:2048", "-nodes",
        "-keyout", join(staging, "privkey.pem"),
        "-out", join(staging, "fullchain.pem"),
        "-days", "3650",
        "-subj", `/CN=${domain}`,
        "-addext", `subjectAltName=DNS:${domain}`,
      ]);
      // Same atomic pair-swap as stageCertDir: OpenResty must never see a cert
      // beside a key that doesn't open it.
      await this._mkdir(dir);
      if (this.executor) {
        await this.executor.exec(
          `mv -f ${sq(join(staging, "fullchain.pem"))} ${sq(join(staging, "privkey.pem"))} ${sq(dir)}/`,
        );
      } else {
        await fsRename(join(staging, "fullchain.pem"), certPath);
        await fsRename(join(staging, "privkey.pem"), keyPath);
      }
      return { certPath, keyPath };
    } catch (err) {
      console.warn(
        `[SSL] could not create a temporary certificate for ${domain} — serving HTTP only until ` +
          `a real certificate is issued (is openssl installed on the edge?): ${safeErrorMessage(err)}`,
      );
      return null;
    } finally {
      await this._rm(staging).catch(() => undefined);
    }
  }

  private async _exec(command: string, args: string[] = []): Promise<string> {
    if (this.executor) {
      // Remote path runs through a login shell (ssh2 exec), so every arg MUST
      // be shell-quoted — otherwise a value like an ACME email carrying `;`,
      // `$()`, or backticks executes as a command on the managed server (root).
      // The local branch below is argv-based (execFile) and needs no quoting.
      const full = args.length ? `${command} ${args.map(sq).join(" ")}` : command;
      return this.executor.exec(full);
    }
    try {
      const { stdout } = await execFileAsync(command, args);
      return stdout;
    } catch (err) {
      // execFile's error carries stdout/stderr as props but NOT in .message
      // ("Command failed: certbot …"). Fold them in so the caller (and the
      // certbot summarizer) sees the real output, not just the exit boilerplate.
      const e = err as { stdout?: string; stderr?: string; message?: string };
      const detail = [e.stderr?.trim(), e.stdout?.trim()].filter(Boolean).join("\n");
      throw new Error(detail || e.message || String(err));
    }
  }

  /**
   * Does this static `root` resolve where OpenResty looks? (RoutingProvider)
   *
   * Runs the probe through `this.executor` — the SAME handle vhost writes and
   * `openresty -s reload` go through — so it answers from the edge's own vantage
   * point. That is the whole value: for a containerized edge the executor's `exec`
   * lands INSIDE the container (DockerEdgeExecutor / edgeContainerExecutor), so a
   * `root` that exists on the host but was never bind-mounted reads as missing
   * here, which is exactly the 404 a host-side probe cannot see. With no executor
   * the edge is bare-local and shares this process's filesystem, so node:fs is
   * already the right vantage point.
   *
   * Advisory: never throws.
   */
  async probeStaticRoot(servedPath: string): Promise<OutputProbeResult> {
    if (this.executor) return probeStaticOutput(this.executor, servedPath);
    const found = await this._exists(servedPath);
    if (!found) return { found: false, hasIndex: false, checked: true };
    // A file IS its own index; a directory needs index.html to serve at that path.
    const isFile = await fsStat(servedPath)
      .then((s) => s.isFile())
      .catch(() => false);
    const hasIndex = isFile || (await this._exists(join(servedPath, "index.html")));
    return { found: true, hasIndex, checked: true };
  }

  /**
   * Run certbot, optionally STREAMING its output line-by-line to `onLog` (the
   * live verify modal). Falls back to buffered `_exec` when no callback / no
   * executor. `streamExec` doesn't reject on a non-zero exit — it returns the
   * code — so mirror `_exec`'s throw-with-output so `summarizeCertbotFailure`
   * still sees the real cause.
   */
  private async _execCertbot(args: string[], onLog?: (line: string) => void): Promise<string> {
    const command = this.acmeCaBundle ? "env" : "certbot";
    const commandArgs = this.acmeCaBundle
      ? [`REQUESTS_CA_BUNDLE=${this.acmeCaBundle}`, "certbot", ...args]
      : args;
    if (!onLog || !this.executor) {
      let out: string;
      try {
        out = await this._exec(command, commandArgs);
      } catch (err) {
        // Redact HERE, not only in callers' catches — renewCert has none, and a
        // new caller must not be able to leak the EAB key by forgetting one.
        throw new Error(this.redactAcmeSecrets(safeErrorMessage(err)));
      }
      const redacted = this.redactAcmeSecrets(out);
      if (redacted) onLog?.(redacted);
      return redacted;
    }
    const full = `${command} ${commandArgs.map(sq).join(" ")}`;
    // Accumulate RAW output and redact the whole buffer at each use: per-chunk
    // redaction alone misses a secret split across a chunk boundary.
    let output = "";
    const { code } = await this.executor.streamExec(full, (log) => {
      output += log.message;
      onLog(this.redactAcmeSecrets(log.message));
    });
    if (code !== 0) {
      throw new Error(this.redactAcmeSecrets(output).trim() || `certbot exited ${code}`);
    }
    return this.redactAcmeSecrets(output);
  }

  private redactAcmeSecrets(value: string): string {
    return this.acmeEabHmacKey
      ? value.split(this.acmeEabHmacKey).join("[REDACTED]")
      : value;
  }

  /**
   * Keep EAB HMAC material out of argv/process listings and remove it after use.
   *
   * Same layout contract as runtime/git-ssh-material.ts (the repo's other
   * ephemeral-secret-on-disk site): the material lives in its OWN 0700 directory
   * with the file at 0600, the bytes never travel through a shell command line,
   * and cleanup removes the directory as a unit. The 0700 parent goes first, so
   * even the temp file _writeFile stages is born unreadable to other users.
   */
  private async createEphemeralEabConfig(): Promise<string | null> {
    if (!this.acmeEabKid || !this.acmeEabHmacKey) return null;
    const dir = join(dirname(this.certDir), `.openship-eab-${randomBytes(12).toString("hex")}`);
    const path = join(dir, "eab.ini");
    if (this.executor) {
      await this.executor.mkdir(dir);
      await this._exec("chmod", ["700", dir]);
    } else {
      await fsMkdir(dir, { recursive: true, mode: 0o700 });
    }
    try {
      await this._writeFile(
        path,
        `eab-kid = ${this.acmeEabKid}\neab-hmac-key = ${this.acmeEabHmacKey}\n`,
        0o600,
      );
    } catch (err) {
      // A partial write must not leave key material behind (git-ssh-material rule).
      await this._rm(dir).catch(() => undefined);
      throw err;
    }
    return path;
  }

  private async _captureFile(path: string): Promise<FileSnapshot> {
    if (!(await this._exists(path))) {
      return { exists: false };
    }

    return {
      exists: true,
      content: await this._readFile(path),
    };
  }

  private async _restoreFile(path: string, snapshot: FileSnapshot): Promise<void> {
    if (!snapshot.exists) {
      await this._rm(path);
      return;
    }

    await this._writeFile(path, snapshot.content ?? "");
  }

  // ── Routing ──────────────────────────────────────────────────────────

  /**
   * Register a route by writing an OpenResty server block.
   *
   * Creates a conf file in sites-enabled, then reloads.
   * If TLS is enabled and certs exist, configures SSL. If certs don't
   * exist yet, writes an HTTP-only block (certbot will add SSL later
   * via provisionCert).
   */
  async registerRoute(route: RouteConfig): Promise<void> {
    assertValidDomain(route.domain);
    await this._mkdir(this.sitesDir);

    const slug = await this.resolveSlug(route.domain);
    const configPath = join(this.sitesDir, `${slug}.conf`);
    if ("staticRoot" in route && route.staticRoot) {
      assertValidStaticRoot(route.staticRoot, { adopted: route.staticRootAdopted });
    } else {
      assertValidUpstream((route as { targetUrl: string }).targetUrl);
    }
    // A canonical host redirect REPLACES the body — this host serves no content of
    // its own, so the upstream/root is validated above (the destination is kept so
    // dropping the redirect restores a serving route) but never emitted.
    const hostRedirect = renderHostRedirect(route);
    const locationBody = hostRedirect
      ? hostRedirect
      : "staticRoot" in route && route.staticRoot
      ? `root ${route.staticRoot};
        index index.html;
        try_files $uri $uri/ /index.html;`
      : `proxy_pass ${(route as { targetUrl: string }).targetUrl};
        ${PROXY_HEADERS}`;

    // Composite single-domain: extra path-prefix proxy locations (e.g. /api/ →
    // backend) + vercel.json redirects, emitted BEFORE `location /` so nginx
    // longest-prefix / exact match routes them ahead of the primary target.
    // Suppressed for a redirecting host: a path that proxied while everything else
    // redirected would be a split-brain vhost, and a webhook POST would lose its
    // body to the 301. (ACME_CHALLENGE_LOCATION is emitted separately below and
    // deliberately KEPT — a redirecting host still issues its own certificate.)
    const extraLocations = hostRedirect
      ? ""
      : `${renderRedirects(route)}${renderProxyLocations(route)}`;
    // Global response headers (vercel.json `headers` with source "/(.*)").
    const serverHeaders = hostRedirect ? "" : renderServerHeaders(route);
    // Curated reverse-proxy tunables (client_max_body_size, timeouts, gzip, …).
    // Server-scope so they cover `location /` + every extra location, and
    // override the server-wide http default for this vhost.
    const proxyOpts = renderProxyOptions(route.proxy);

    // Optional: webhook proxy location for GitHub push delivery. Never on a
    // redirecting host — a 30x would drop the delivery's POST body.
    const webhookLocation = route.webhookProxy && !hostRedirect
      ? `
    location /_openship/hooks/ {
        proxy_pass ${route.webhookProxy};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $openship_fwd_proto;
    }
`
      : "";

    // Fail-safe: only emit the Lua directives when the scripts are actually
    // installable. On a build that dropped the Lua from its bundle, referencing
    // a missing file makes OpenResty 500 EVERY request (total outage). Omitting
    // them means the edge rules-engine + analytics logging are off, but the site
    // SERVES. luaSourceAvailable() is the same signal the installer gates on.
    const edgeLua = luaSourceAvailable();
    const luaProxy = edgeLua
      ? `    log_by_lua_file ${LUA_LOGGER_PATH};\n    access_by_lua_file ${RULES_GUARD_PATH};`
      : "";

    // `location /` for a block that serves the app.
    const serveLocation = `    location / {
        ${locationBody}
    }`;

    // `location /` for the :80 block of a route that has a real cert: send the
    // visitor to https — unless a CDN already terminated TLS and reached us on
    // :80, in which case serving is the only non-looping answer (FORWARD_VARS).
    // `return` inside `if` is one of the documented-safe uses of `if`; proxy_pass
    // stays outside it.
    //
    // A canonical redirect skips that dance and goes straight to the target from
    // :80 as well: bouncing to our OWN https first would cost a second round trip
    // to reach the same place, and there's no CDN loop to avoid because the
    // destination is a DIFFERENT host.
    const redirectOrServeLocation = hostRedirect
      ? serveLocation
      : `    location / {
        if ($openship_redirect_https) {
            return 301 https://$server_name$request_uri;
        }

        ${locationBody}
    }`;

    // Everything both server blocks share, after the per-block preamble.
    const sharedBody = `${serverHeaders}${proxyOpts}
${webhookLocation}${extraLocations}`;

    // No TLS listener: either TLS isn't ours to terminate for this host, or a
    // placeholder cert couldn't be produced. provisionCert() re-registers with the
    // SSL block once a real cert lands.
    const httpOnlyBlock = `# Auto-generated by Openship - do not edit manually
server {
    listen 80;
    server_name ${route.domain};

${FORWARD_VARS}

${luaProxy}

${ACME_CHALLENGE_LOCATION}
${sharedBody}
${serveLocation}
}
`;

    let serverBlock: string;
    let bootstrapServed = false;

    if (route.tls && (await this.certsExist(route.domain))) {
      const certPath = join(this.certDir, route.domain, "fullchain.pem");
      const keyPath = join(this.certDir, route.domain, "privkey.pem");
      // Full SSL config - certs already provisioned. The :80 block carries the
      // full app body too (not just a redirect), because behind a TLS-terminating
      // CDN it is the block that actually serves — including the rules guard, so
      // rate limits / bans / country rules can't be bypassed by arriving on :80.
      serverBlock = `# Auto-generated by Openship - do not edit manually
server {
    listen 80;
    server_name ${route.domain};

${FORWARD_VARS}

${luaProxy}

${ACME_CHALLENGE_LOCATION}
${sharedBody}
${redirectOrServeLocation}
}

server {
    listen 443 ssl;
    server_name ${route.domain};

${FORWARD_VARS}

${luaProxy}

    ssl_certificate ${certPath};
    ssl_certificate_key ${keyPath};
${sharedBody}
${serveLocation}
}
`;
    } else if (route.tls && route.terminatesTlsLocally) {
      // TLS is ours to terminate but there's no cert yet. Serve a temporary
      // self-signed one rather than NOTHING on :443 — see ensureBootstrapCert for
      // why a missing :443 block is a hard failure (#308), not a soft one.
      //
      // :80 serves the app and does NOT redirect: plain HTTP has to stay
      // answerable for the ACME challenge, a CDN on Flexible must not loop, and
      // pushing a browser onto an untrusted cert is worse than serving HTTP.
      const bootstrap = await this.ensureBootstrapCert(route.domain);
      bootstrapServed = !!bootstrap;
      serverBlock = bootstrap
        ? `# Auto-generated by Openship - do not edit manually
# openship-bootstrap-tls: ${route.domain} is serving a TEMPORARY self-signed
# certificate because its real certificate has not been issued yet. Openship
# replaces this file automatically once it lands. Do not adopt this material.
server {
    listen 80;
    server_name ${route.domain};

${FORWARD_VARS}

${luaProxy}

${ACME_CHALLENGE_LOCATION}
${sharedBody}
${serveLocation}
}

server {
    listen 443 ssl;
    server_name ${route.domain};

${FORWARD_VARS}

${luaProxy}

    ssl_certificate ${bootstrap.certPath};
    ssl_certificate_key ${bootstrap.keyPath};
${sharedBody}
${serveLocation}
}
`
        : httpOnlyBlock;
    } else {
      // No TLS here (external ingress terminates it, or a managed *.opsh.io host
      // Openship Cloud's edge fronts) — HTTP-only, and no placeholder cert: we
      // must never present one for a hostname whose TLS isn't ours.
      serverBlock = httpOnlyBlock;
    }

    // Snapshot the prior conf so a block that fails `openresty -t` can be
    // rolled back — otherwise a bad conf stays on disk and poisons every
    // subsequent reload box-wide (same self-rollback applyRateLimit uses).
    const snapshot = await this._captureFile(configPath);
    await this._writeFile(configPath, serverBlock);
    try {
      await this.reload();
    } catch (err) {
      await this._restoreFile(configPath, snapshot);
      await this.reload().catch(() => undefined);
      throw err;
    }

    // The conf we just loaded doesn't reference the placeholder, so nothing is
    // serving it — drop it. Keyed on what was EMITTED rather than on "a real cert
    // arrived", so this also converges a host that stops terminating TLS here
    // (external ingress, or a caller that claimed the flag too broadly) instead of
    // leaving stale key material and a stale listener behind.
    //
    // AFTER the reload, never before: until the new conf is actually running,
    // OpenResty is still reading the bootstrap paths, and removing them first would
    // break TLS for the domain on the next unrelated reload.
    if (!bootstrapServed) {
      await this._rm(this.bootstrapCertDir(route.domain)).catch(() => undefined);
    }

    // Persist the full RouteConfig alongside the conf so `provisionCert` can
    // re-register the EXACT route (proxyLocations + webhookProxy) after issuing a
    // cert, instead of regex-reconstructing it from the generated conf (which
    // only recovered the primary target and dropped composite locations).
    await this._writeFile(this.routeStatePath(slug), JSON.stringify(route)).catch(() => undefined);
  }

  private routeStatePath(slug: string): string {
    return join(this.sitesDir, `${slug}.route.json`);
  }

  /**
   * Remove a route by deleting its conf + route-state files, then reload.
   *
   * Self-rollback (same pattern as registerRoute): snapshot both files first, and
   * if the post-removal `openresty -t`/reload fails — usually because an UNRELATED
   * vhost is broken — restore them so the edge on disk == the running config.
   * Without this, a failed reload left the route GONE from disk but still served
   * from the old in-memory config (an inconsistent half-state that would silently
   * vanish on the next unrelated reload). The error is re-thrown for retry.
   */
  async removeRoute(domain: string): Promise<void> {
    assertValidDomain(domain);
    const slug = await this.resolveSlug(domain);
    const configPath = join(this.sitesDir, `${slug}.conf`);
    const statePath = this.routeStatePath(slug);
    const confSnapshot = await this._captureFile(configPath);
    const stateSnapshot = await this._captureFile(statePath);
    await this._rm(configPath);
    await this._rm(statePath).catch(() => undefined);
    try {
      await this.reload();
    } catch (err) {
      await this._restoreFile(configPath, confSnapshot);
      await this._restoreFile(statePath, stateSnapshot);
      await this.reload().catch(() => undefined);
      throw err;
    }

    // Nothing references the placeholder cert once the vhost is gone. Real certs
    // in certbot's tree are deliberately left alone (a re-add reuses them); this
    // material is disposable by construction.
    await this._rm(this.bootstrapCertDir(domain)).catch(() => undefined);
  }

  // ── SSL ──────────────────────────────────────────────────────────────

  /**
   * Provision a TLS certificate using certbot.
   *
   * Runs `certbot certonly` in webroot mode using the ACME challenge
   * directory served by OpenResty, then rewrites the config to include
   * SSL and reloads.
   *
   * Only --webroot is attempted. The previous --standalone fallback was
   * dead code on any normal install: certbot --standalone binds to port
   * 80 itself, but OpenResty already owns 80 on the same box, so the
   * fallback would always fail with EADDRINUSE — amplifying a transient
   * --webroot failure into an immediate hard error. The caller
   * (route-registration.ts) already wraps provisionCert in try/catch so
   * a webroot failure becomes a "deploy continues on HTTP, retry from
   * Domains tab" warning instead of a deploy abort.
   */
  async provisionCert(
    domain: string,
    opts?: { onLog?: (line: string) => void; force?: boolean },
  ): Promise<SslResult> {
    assertValidDomain(domain);

    // Reuse an existing cert unless the caller forces a reissue. `force` is set
    // when the service layer has already decided the current cert is missing /
    // near-expiry / a deliberate renew — without it this short-circuit would
    // return a stale cert and a renewal would silently no-op.
    if (!opts?.force && (await this.certsExist(domain))) {
      return this.readCertInfo(domain);
    }

    // Defense-in-depth: only pass acmeEmail when it's a plausible address.
    // (_exec now shell-quotes every arg, but a garbage/injection-shaped value
    // has no business reaching certbot — drop it rather than register with it.)
    const validEmail = !!this.acmeEmail && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.acmeEmail);
    const emailArgs = validEmail
      ? ["--email", this.acmeEmail as string]
      : ["--register-unsafely-without-email"];

    let certonlyOut = "";
    const eabConfig = await this.createEphemeralEabConfig();
    try {
      // ACME via certbot's STANDALONE authenticator on a loopback alt-port; the
      // edge proxies /.well-known/acme-challenge/ → 127.0.0.1:<port> (see
      // ACME_CHALLENGE_LOCATION). Zero downtime — no port-80 fight with the edge,
      // no webroot dependency, no DNS-01. Works bare (host netns) and docker-edge
      // (container netns) alike, since certbot runs on the same executor as the
      // edge it's proxied through.
      //
      // `--cert-name <domain>` PINS the lineage to the bare domain name. Without
      // it, certbot appends `-0001`/`-0002` when a stale renewal config for the
      // domain lingers (a prior teardown/migration removed the live symlink but
      // left /etc/letsencrypt/renewal), so the cert lands at `<domain>-0001` while
      // certsExist/readCertInfo only ever look at `<domain>` → an eternal
      // "missing", and a re-run just prints "not due for renewal" (exit 0). Pinning
      // the name makes the on-disk path deterministic and self-heals that state.
      certonlyOut = await this._execCertbot([
        ...(eabConfig ? ["--config", eabConfig] : []),
        "certonly", "--standalone", "--http-01-port", String(ACME_HTTP01_PORT),
        "--cert-name", domain, "-d", domain,
        ...(this.acmeDirectoryUrl ? ["--server", this.acmeDirectoryUrl] : []),
        ...acmeKeyArgs(this.acmeKeyType),
        ...emailArgs,
        ...(this.acmeTosAgreed ? ["--agree-tos"] : []),
        "--non-interactive",
        // Forced reissue: certbot would otherwise print "not due for renewal"
        // (exit 0) when a lineage exists, leaving the stale cert in place.
        ...(opts?.force ? ["--force-renewal"] : []),
      ], opts?.onLog);
    } catch (err) {
      // Replace certbot's opaque opener with the real, actionable cause.
      throw new Error(summarizeCertbotFailure(this.redactAcmeSecrets(safeErrorMessage(err)), domain));
    } finally {
      // Remove the whole 0700 directory, not just the ini — one unit, like
      // git-ssh-material's cleanup.
      if (eabConfig) await this._rm(dirname(eabConfig)).catch(() => undefined);
    }

    // Rewrite the config with SSL now that certs exist
    const slug = await this.resolveSlug(domain);
    const configPath = join(this.sitesDir, `${slug}.conf`);

    // Prefer the persisted RouteConfig sidecar so the re-register keeps every
    // location (composite proxyLocations + webhookProxy), not just the primary.
    try {
      const state = await this._readFile(this.routeStatePath(slug));
      const saved = JSON.parse(state) as RouteConfig;
      await this.registerRoute({ ...saved, domain, tls: true });
      return this.ensureIssued(domain, certonlyOut);
    } catch {
      // No sidecar (legacy route or unreadable) - fall back to scraping the conf.
    }

    try {
      const existing = await this._readFile(configPath);
      const targetMatch = existing.match(/proxy_pass\s+([^;]+);/);
      if (targetMatch) {
        await this.registerRoute({ domain, targetUrl: targetMatch[1], tls: true });
        return this.ensureIssued(domain, certonlyOut);
      }

      const rootMatch = existing.match(/root\s+([^;]+);/);
      if (rootMatch) {
        // Re-registering the root from OUR OWN existing vhost to add TLS. It passed
        // the floor when first written (possibly as adopted), so re-checking it here
        // would reject a legitimately imported site at cert time.
        await this.registerRoute({
          domain,
          staticRoot: rootMatch[1],
          staticRootAdopted: true,
          tls: true,
        });
        return this.ensureIssued(domain, certonlyOut);
      }
    } catch {
      // Config doesn't exist - cert provisioned but no route yet
    }

    return this.ensureIssued(domain, certonlyOut);
  }

  /**
   * After a certbot run that DIDN'T throw, confirm a usable cert actually landed
   * at the expected path. certbot can exit 0 while producing nothing readable
   * there (a lineage written elsewhere, "not due for renewal", 0 domains
   * authenticated) — a silent `{missing}` hides why. Surface certbot's real
   * output so the operator sees the actual reason instead of a generic message.
   */
  private async ensureIssued(domain: string, certbotOutput: string): Promise<SslResult> {
    const result = await this.readCertInfo(domain);
    if (result.verified) return result;
    const tail = certbotOutput.trim().slice(-1200);
    throw new Error(
      summarizeCertbotFailure(certbotOutput, domain) +
        (tail ? `\n\ncertbot exited without an error but no readable certificate is at ` +
          `${join(this.certDir, domain)}. certbot said:\n${tail}` : ""),
    );
  }

  /**
   * Renew a TLS certificate using certbot.
   */
  async renewCert(domain: string): Promise<SslResult> {
    assertValidDomain(domain);

    // `certbot renew` only acts on certs that ALREADY exist. A domain that
    // never got its first cert (initial provision failed, or was skipped)
    // has nothing to renew — certbot exits 0 doing nothing, so the caller
    // sees "renewed" while the domain stays stuck in `provisioning`. When no
    // cert exists yet, "renew" must mean "obtain the first one" → delegate to
    // provisionCert (certbot certonly), which also rewrites the vhost with the
    // 443/ssl block and reloads. This is what makes the Renew button able to
    // bootstrap a domain that has only an HTTP vhost.
    if (!(await this.certsExist(domain))) {
      return this.provisionCert(domain);
    }

    // A cert can be on disk WITHOUT being a certbot lineage — an ACME cert adopted
    // from a foreign proxy (migration / cert reuse) is written straight to certbot's
    // path, but certbot has no renewal config for it, and `certbot renew
    // --cert-name` fails outright with "no certificate found with name". Such a cert
    // IS ours to reissue (public ACME CA, this box owns the domain), so renewing it
    // means obtaining a first lineage — `certonly` with force, not `renew`.
    if (!(await this.hasCertbotLineage(domain))) {
      return this.provisionCert(domain, { force: true });
    }

    // A lineage issued by a DIFFERENT directory than the one now configured can't
    // be renewed against the new CA — `renew` won't register the account the new
    // server requires (or carry EAB). Reissue instead: certonly registers under
    // the configured CA and rewrites the lineage, so this heals itself once.
    if (!(await this.lineageServerMatches(domain))) {
      return this.provisionCert(domain, { force: true });
    }

    // No `--server` here: the matched lineage's conf already records it, and the
    // mismatch case above never reaches this call.
    await this._execCertbot([
      "renew", "--cert-name", domain,
      ...acmeKeyArgs(this.acmeKeyType),
      "--non-interactive",
    ]);
    await this.reload();

    return this.readCertInfo(domain);
  }

  /**
   * Does certbot track a renewal lineage for this domain? `/etc/letsencrypt/renewal/
   * <domain>.conf` is the per-lineage record certbot writes on first issuance and
   * reads on every `renew`, so its presence is the authoritative answer — the cert
   * FILES existing is not (they can be adopted, or copied in by hand).
   */
  private renewalConfPath(domain: string): string {
    // Derived from certDir so a custom cert root (tests, container edge) stays
    // consistent: /etc/letsencrypt/live → /etc/letsencrypt/renewal.
    return join(dirname(this.certDir), "renewal", `${domain}.conf`);
  }

  private async hasCertbotLineage(domain: string): Promise<boolean> {
    return this._exists(this.renewalConfPath(domain));
  }

  /**
   * Was this lineage issued by the CURRENTLY configured ACME directory? The
   * renewal conf records the issuing `server`, and `certbot renew` only holds an
   * account for THAT server — after the operator points at a different CA, renewing
   * a pre-switch lineage would need an account registration `renew` cannot perform
   * (and EAB material it is never given). An unreadable/unparsable conf answers
   * `true` so the plain renew still runs and surfaces certbot's own error.
   */
  private async lineageServerMatches(domain: string): Promise<boolean> {
    let conf: string;
    try {
      conf = await this._readFile(this.renewalConfPath(domain));
    } catch {
      return true;
    }
    const recorded = conf.match(/^\s*server\s*=\s*(\S+)\s*$/m)?.[1];
    if (!recorded) return true;
    const effective = this.acmeDirectoryUrl ?? LETSENCRYPT_PRODUCTION_DIRECTORY;
    return recorded === effective;
  }

  /**
   * Install an operator-supplied or adopted certificate (no ACME). Validates the
   * PEM pair against the domain, writes it to the same on-disk path certbot uses,
   * then re-registers the vhost with TLS — mirroring provisionCert's tail so
   * composite routes are preserved.
   *
   * The validation is deliberately here, at the last gate before disk, and not
   * only in the callers: every path that puts a cert on this box (operator upload,
   * migration carry, cert reuse) funnels through this method, so a check here can't
   * be bypassed by a new caller that forgets it.
   */
  async installCert(domain: string, cert: ManualCert): Promise<SslResult> {
    assertValidDomain(domain);

    // Validate before touching disk. The pair must parse and the key must match,
    // or OpenResty fails to reload — which takes down every OTHER domain on this
    // edge too, not just this one. The coverage and expiry checks are what keep a
    // cert for a DIFFERENT hostname (an adopted vhost naming several hosts off one
    // single-name cert) from being served under a green padlock.
    const candidate = validateCertFor(domain, cert, "supplied certificate");
    if (!candidate.cert) throw new Error(`Invalid certificate: ${candidate.reason}`);
    const { expiresAt } = candidate.cert;

    // Stage both PEMs in a sibling dir and swap it in with ONE rename. Writing the
    // two files in place is not atomic: a failure between them leaves the new cert
    // beside the old key, which is exactly the mismatched pair that breaks the
    // reload for the whole edge.
    const dir = join(this.certDir, domain);
    await this.stageCertDir(dir, cert);

    // Re-register the vhost with TLS now that the cert is on disk. Prefer the
    // persisted RouteConfig sidecar so every location survives (same as
    // provisionCert); if there's no route yet, the next deploy's route plan
    // picks up tls:true from the manualSsl gate.
    const slug = await this.resolveSlug(domain);
    try {
      const state = await this._readFile(this.routeStatePath(slug));
      const saved = JSON.parse(state) as RouteConfig;
      await this.registerRoute({ ...saved, domain, tls: true });
    } catch {
      // No sidecar (domain not routed yet) — cert is staged on disk regardless.
    }

    return {
      domain,
      expiresAt,
      issuer: candidate.cert.renewable ? candidate.cert.issuer : "manual",
      verified: true,
      reason: "issued",
    };
  }

  // ── Helpers ──────────────────────────────────────────────────────────

  /**
   * Filename stem for a domain. NOT injective — see `resolveSlug`.
   *
   * Kept exactly as-is on purpose: it names every vhost file on every existing
   * install, so changing it would rename the lot and leave the old names behind
   * still serving. `resolveSlug` handles the collisions instead.
   */
  private domainSlug(domain: string): string {
    return domain.replace(/[^a-zA-Z0-9-]/g, "-").replace(/-+/g, "-");
  }

  /** Deterministic per-domain disambiguator for a slug collision. */
  private slugSuffix(domain: string): string {
    return createHash("sha1").update(domain).digest("hex").slice(0, 8);
  }

  /** Every `server_name` token declared in a vhost body. */
  private serverNamesIn(conf: string): string[] {
    const names: string[] = [];
    for (const m of conf.matchAll(/server_name\s+([^;]+);/g)) {
      for (const tok of m[1]!.trim().split(/\s+/)) {
        if (tok) names.push(tok.toLowerCase().replace(/\.$/, ""));
      }
    }
    return names;
  }

  /**
   * The slug THIS domain's files live under.
   *
   * `domainSlug` folds every non-alphanumeric to `-`, so a dot and a literal dash
   * collapse together and two different, separately-claimable hostnames land on
   * one filename:
   *
   *     staging.app.example.com  ->  staging-app-example-com
   *     staging-app.example.com  ->  staging-app-example-com
   *
   * Both are ordinary hostnames and can belong to different projects — even
   * different orgs, since one edge fronts the whole box. Whichever registered last
   * silently overwrote the other's vhost, and the loser's traffic fell through to
   * `default_server`: a silent outage of somebody else's domain. `removeRoute` on
   * either one deleted the shared file and took out both.
   *
   * Resolution, in this order, and the order is the whole correctness argument:
   *
   *   1. A disambiguated file for this domain already exists → keep using it.
   *      MUST come first. If the incumbent is later removed, step 3 would hand
   *      this domain the now-free base name while its real conf stayed on disk
   *      under the suffixed name — two files serving one hostname, which is the
   *      exact orphan class this whole change exists to remove.
   *   2. The base file exists and does NOT list this domain in its `server_name`
   *      → it is someone else's. Take a suffixed name; the incumbent is untouched.
   *   3. Otherwise the base name is ours (free, or already ours).
   *
   * Containment, not equality, in step 2 — and the reason is narrower than it
   * looks. Everything WE write carries exactly one `server_name` (see the server
   * blocks above), and a takeover fans out one `registerRoute` per hostname
   * (`registerImportedSites`), so no Openship-managed conf ever lists two. The
   * only file that can is one the operator placed in `sites-enabled` themselves.
   *
   * For that file, reusing it is the lesser evil, not a free win: we rewrite it
   * with a single `server_name`, so a sibling hostname it also served stops being
   * served. The alternative is worse — a second vhost answering a name the first
   * one already claims makes OpenResty warn "conflicting server name" and silently
   * keep the FIRST, so the route we were asked to create would not take effect at
   * all. Losing the sibling is at least the outcome the caller asked for.
   */
  private async resolveSlug(domain: string): Promise<string> {
    const base = this.domainSlug(domain);
    const suffixed = `${base}-${this.slugSuffix(domain)}`;
    const host = domain.toLowerCase().replace(/\.$/, "");

    if (await this._exists(join(this.sitesDir, `${suffixed}.conf`)).catch(() => false)) {
      return suffixed;
    }

    const basePath = join(this.sitesDir, `${base}.conf`);
    if (await this._exists(basePath).catch(() => false)) {
      const conf = await this._readFile(basePath).catch(() => "");
      // Unreadable/empty → treat as ours rather than fragmenting on a read blip.
      if (conf) {
        const names = this.serverNamesIn(conf);
        if (names.length > 0 && !names.includes(host)) return suffixed;
      }
    }
    return base;
  }

  /**
   * Re-detect OpenResty paths and reload.
   *
   * Paths can become stale after an OpenResty reinstall (the binary or
   * config may move). Re-detecting on every reload keeps the provider
   * in sync without requiring an API restart.
   */
  private async reload(): Promise<void> {
    if (this.executor) {
      if (!this.pinPaths) {
        try {
          const freshPaths = await detectOpenRestyPaths(this.executor);
          this.sitesDir = freshPaths.sitesDir;
          this.reloadCommand = buildReloadCommand(freshPaths, {
            containerEdge: this.containerEdge,
          });
        } catch {
          // Detection failed - fall through with current cached paths
        }
      }
      await this.executor.exec(this.reloadCommand);
      return;
    }

    await execFileAsync("sh", ["-lc", this.reloadCommand]);
  }

  private async certsExist(domain: string): Promise<boolean> {
    const certPath = join(this.certDir, domain, "fullchain.pem");
    if (this.executor) {
      return this.executor.exists(certPath);
    }
    try {
      await fsReadFile(certPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Read the on-disk cert and report its validity. Distinguishes three cases so
   * the caller never downgrades a healthy domain on a transient hiccup:
   *   - file present + parses  → verified, real expiry
   *   - file ABSENT            → not verified, reason "missing"  (no cert yet)
   *   - file present, unreadable/unparseable → not verified, reason "read_error"
   */
  private async readCertInfo(domain: string): Promise<SslResult> {
    if (!(await this.certsExist(domain))) {
      return { domain, expiresAt: "", issuer: "certbot", verified: false, reason: "missing" };
    }
    let certPem: string;
    let keyPem: string;
    try {
      certPem = await this._readFile(join(this.certDir, domain, "fullchain.pem"));
      keyPem = await this._readFile(join(this.certDir, domain, "privkey.pem"));
    } catch {
      // The file exists but couldn't be read (SSH blip, permissions, partial
      // write). Transient — the caller must NOT treat this as "no cert".
      return { domain, expiresAt: "", issuer: "certbot", verified: false, reason: "read_error" };
    }

    // `verified` used to be true for ANY parseable cert, so an EXPIRED cert — or a
    // pair whose key doesn't open it, or one issued for a different hostname — read
    // as healthy. That made "Recheck SSL" report green on a cert browsers reject,
    // let a deploy short-circuit past reissuing an expired cert, and let cert reuse
    // adopt whatever happened to be sitting at this path (including a cert a
    // cross-server migration had just carried in).
    const candidate = validateCertFor(domain, { certPem, keyPem }, "on-disk certificate");
    if (!candidate.cert) {
      // Logged because `reason` is a fixed enum: without this line the operator sees
      // "provisioning" with no way to learn the cert on disk is expired vs. for the
      // wrong name — two problems with very different fixes.
      console.warn(`[SSL] unusable cert on disk for ${domain}: ${candidate.reason}`);
      return { domain, expiresAt: "", issuer: "certbot", verified: false, reason: "invalid" };
    }
    return {
      domain,
      expiresAt: candidate.cert.expiresAt,
      issuer: candidate.cert.issuer || "certbot",
      verified: true,
    };
  }

  /**
   * Read-only check that the Let's Encrypt cert is actually present + valid on
   * the serving host. No certbot, no config rewrite — safe to call any time
   * (deploy, "Recheck SSL" button).
   */
  async verifyCert(domain: string): Promise<SslResult> {
    assertValidDomain(domain);
    return this.readCertInfo(domain);
  }

  // ── Rate Limiting ──────────────────────────────────────────────────

  /** Dedicated include dir for Openship-managed OpenResty snippets. */
  private get rateLimitIncludeDir(): string {
    return join(dirname(this.sitesDir), "openship-includes");
  }

  /** Path to the managed rate-limit snippet inside the dedicated include dir. */
  private get rateLimitConfPath(): string {
    return join(this.rateLimitIncludeDir, "ratelimit.conf");
  }

  /**
   * Apply rate limit configuration to OpenResty.
   *
   * Writes a `ratelimit.conf` snippet with geo whitelist, map, and
   * limit_req_zone directives. Ensures an `include` for it exists in
   * nginx.conf's http block. Then validates + reloads.
   *
   * Pass rps=0 to disable rate limiting entirely.
   */
  async applyRateLimit(config: RateLimitConfig): Promise<void> {
    const confPath = this.rateLimitConfPath;
    const nginxConfPath = join(dirname(this.sitesDir), "nginx.conf");
    const snapshots = {
      nginx: await this._captureFile(nginxConfPath),
      current: await this._captureFile(confPath),
    };

    // Build geo block - whitelist loopback + user-specified CIDRs
    const geoEntries = renderGeoEntries(config.whitelist);

    const snippet = `# Auto-generated by Openship - rate limit config
# Edit via Settings > Rate Limiting in the dashboard

geo $whitelist {
${geoEntries.join("\n")}
    }

    map $whitelist $limit_key {
        1   "";
        0   $binary_remote_addr;
    }

    limit_req_zone $limit_key zone=global_limit:10m rate=${config.rps}r/s;
    limit_req zone=global_limit burst=${config.burst} nodelay;
    limit_req_status 429;
`;

    try {
      await this.ensureRateLimitInclude();

      if (config.rps <= 0) {
        await this._rm(confPath);
      } else {
        await this._mkdir(this.rateLimitIncludeDir);
        await this._writeFile(confPath, snippet);
      }

      await this.reload();
    } catch (err) {
      let rollbackError: string | null = null;

      try {
        await this._restoreFile(confPath, snapshots.current);
        await this._restoreFile(nginxConfPath, snapshots.nginx);
        await this.reload();
      } catch (restoreErr) {
        rollbackError = safeErrorMessage(restoreErr);
      }

      const message = safeErrorMessage(err);
      if (rollbackError) {
        throw new Error(`${message}; rollback failed: ${rollbackError}`);
      }
      throw err;
    }
  }

  /**
   * Read the current rate limit config from the snippet file.
   * Returns a disabled config when the snippet doesn't exist yet.
   * Returns null only when the file exists but couldn't be read or parsed.
   */
  async getRateLimitConfig(): Promise<RateLimitConfig | null> {
    try {
      const confPath = this.rateLimitConfPath;
      if (!(await this._exists(confPath))) {
        return { rps: 0, burst: 0, whitelist: [] };
      }

      const content = await this._readFile(confPath);
      if (content.includes("disabled")) return { rps: 0, burst: 0, whitelist: [] };

      // Parse rps from: rate=50r/s
      const rpsMatch = content.match(/rate=(\d+)r\/s/);
      const rps = rpsMatch ? parseInt(rpsMatch[1], 10) : 50;

      // Parse burst from: burst=20
      const burstMatch = content.match(/burst=(\d+)/);
      const burst = burstMatch ? parseInt(burstMatch[1], 10) : 20;

      // Parse whitelist from geo block - lines with "1;" that aren't default/loopback
      const whitelist: string[] = [];
      const geoBlock = content.match(/geo \$whitelist \{([\s\S]*?)\}/);
      if (geoBlock) {
        const lines = geoBlock[1].split("\n");
        for (const line of lines) {
          const m = line.match(/^\s+([\da-fA-F.:\/]+)\s+1;/);
          if (m && !["127.0.0.1/32", "::1/128"].includes(m[1]) && m[1] !== "default") {
            whitelist.push(m[1]);
          }
        }
      }

      return { rps, burst, whitelist };
    } catch {
      return null;
    }
  }

  /**
   * Ensure nginx.conf includes the rate limit snippet in its http block.
   */
  private async ensureRateLimitInclude(): Promise<void> {
    const confDir = dirname(this.sitesDir);
    const confPath = join(confDir, "nginx.conf");
    const desiredIncludeLine = `include ${this.rateLimitIncludeDir}/*.conf;`;
    const content = await this._readFile(confPath);
    const trailingNewline = content.endsWith("\n");
    const lines = content.split("\n");
    const nextLines: string[] = [];
    let foundDesiredInclude = false;
    let changed = false;

    await this._mkdir(this.rateLimitIncludeDir);

    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed === desiredIncludeLine) {
        if (foundDesiredInclude) {
          // Duplicate include — keep only the first.
          changed = true;
          continue;
        }
        foundDesiredInclude = true;
      }

      nextLines.push(line);
    }

    if (!foundDesiredInclude) {
      const httpIndex = nextLines.findIndex((line) => /^\s*http\s*\{\s*$/.test(line));
      if (httpIndex === -1) {
        throw new Error(`Failed to ensure rate-limit include: ${confPath} is missing an http block`);
      }

      const indent = nextLines[httpIndex].match(/^\s*/)?.[0] ?? "";
      nextLines.splice(httpIndex + 1, 0, `${indent}    ${desiredIncludeLine}`);
      changed = true;
    }

    if (changed) {
      const nextContent = nextLines.join("\n");
      await this._writeFile(confPath, trailingNewline ? `${nextContent}\n` : nextContent);
    }
  }
}
