import { createAuthClient } from "better-auth/react";
import { organizationClient, emailOTPClient } from "better-auth/client/plugins";
import { getAuthBaseUrl } from "@/lib/api/urls";

/**
 * API base URL - auth requests go directly to the selected API origin.
 *
 * Local SaaS uses localhost:4100. Public-host dev and production use
 * api.openship.io so Better Auth can share cookies with app.openship.io.
 */
const AUTH_BASE_URL = getAuthBaseUrl();

export const authClient = createAuthClient({
  baseURL: AUTH_BASE_URL,
  fetchOptions: {
    credentials: "include",
    // Disable retry to prevent infinite loops on 429
    retry: {
      type: "linear",
      attempts: 0,
      delay: 0,
    },
  },
  plugins: [organizationClient(), emailOTPClient()],
});

export const {
  signIn,
  signUp,
  signOut,
  useSession,
} = authClient;

/**
 * Email-OTP helpers (code-based email verification). Proxy-generated by Better
 * Auth from the emailOTP plugin endpoints; accessed via the client object so TS
 * doesn't complain about missing static properties (same pattern as below).
 *   verifyEmail          → POST /email-otp/verify-email        ({ email, otp })
 *   sendVerificationOtp  → POST /email-otp/send-verification-otp ({ email, type })
 */
export const emailOtp = (authClient as any).emailOtp as {
  verifyEmail: (data: { email: string; otp: string }) => Promise<{
    data?: unknown;
    error?: { message?: string; code?: string } | null;
  }>;
  sendVerificationOtp: (data: {
    email: string;
    type: "email-verification" | "sign-in" | "forget-password";
  }) => Promise<{ data?: unknown; error?: { message?: string; code?: string } | null }>;
};

/**
 * Email / password helpers - these are proxy-generated by Better Auth
 * when the server has emailAndPassword enabled. We access them via
 * the client object so TypeScript doesn't complain about missing
 * static properties.
 */
// Better Auth's client proxy (better-auth/dist/client/proxy.mjs) derives the
// HTTP path straight from the accessed property name via camelCase ->
// kebab-case, with no check that the server actually registered a matching
// route - an accessed property that doesn't exist just silently builds a
// 404. The server-side endpoint (better-auth/dist/api/routes/password.mjs)
// is `requestPasswordReset` -> POST /request-password-reset; `forgetPassword`
// was a stale property name from an older Better Auth version that never
// reaches the handler.
export const forgetPassword = (authClient as any).requestPasswordReset as (
  opts: { email: string; redirectTo?: string },
) => Promise<{ error?: { message?: string } }>;

export const resetPassword = (authClient as any).resetPassword as (
  opts: { newPassword: string; token?: string },
) => Promise<{ error?: { message?: string } }>;

export const sendVerificationEmail = (authClient as any).sendVerificationEmail as (
  opts: { email: string; callbackURL?: string },
) => Promise<{ error?: { message?: string } }>;

export const verifyEmail = (authClient as any).verifyEmail as (
  opts: { query: { token: string } },
) => Promise<{ error?: { message?: string } }>;
